spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/personal_brand_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 20
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024

logging:
  level:
    root: WARN
    com.personalbrand: INFO
